# Continuation from ndarray.py 

If you want a copy of a slice from a `ndarray` you need to explicitly run `.copy()`

In [2]:
import numpy as np 
arr = np.arange(10)
arr_slice = arr[5:8].copy()
print(arr_slice)

[5 6 7]


With higher dimensional slicing, you have more options. For example, a 2d array will contain 1d arrays at each index. 

In [3]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2d array:\n", arr2d)

2d array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr2d[2])

[7 8 9]


Access the second element from the second 1d array: 


In [7]:
print(arr2d[2][2])

# or 

print(arr2d[2, 2])

9
9


Note how we refer to the axes of the 2 dimensional array. 
- Axis 0 = rows,
- Axis 1 = columns

In multidimensional arrays, if you omit later indeces when indexing (i.e. you dont specify a value for each dimension in the array when indexing), the result will be a lower dimensional array. 

In [8]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print("3d array:\n", arr3d)

3d array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
print("Indexing 3d array:\n\n", "arr3d[0]\n\n", arr3d[0])

Slicing 3d array:

 arr3d[0]

 [[1 2 3]
 [4 5 6]]


Just like in lower dimensions, both scalar values and arrays can be assigned to this view. **(we say view, because unless we explicitly make a copy, the subsection of the array that has been selected returns a view of the array)**

## Indexing with Slices

A slce selects a range along an axis. Let's select the forst two rows of arr2d

In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# i.e., select up to, but not including, row 2. 
# in other words, select rows 0, 1. 
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

You can also pass more than one slice just like with indexing. 

In [24]:
# select up to the first two rows along the 0th axis, select up to the first column on the 1st axis. 
arr2d[:2, :1]

array([[1],
       [4]])

**Again, by slicing like this, you always obtain array views of the same number of dimensions.**

Remember a colon `:` by itself means to take the entire selection on that axis. Also, assigning to a slice experssion assigns to the whole selection.

## Boolean Indexing